//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Managment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userr
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Email { get; set; }
        public string Rolee { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
